version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:  
      - db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.17.0/24

volumes:
  mysql_data:
